addons:
  ssh_known_hosts: 101.200.237.78
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
deploy:
  provider: script
  script: bash ./deploy_homepage.sh
